{% set name = "hyperopt" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1bf89ae58050bbd32c7307199046117feee245c2fd9ab6255c7308522b7ca149

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pymongo
    - six
    - networkx >=2.2
    - future
    - tqdm
    - setuptools
    - cloudpickle

test:
  imports:
    - hyperopt
    - hyperopt.fmin
    - hyperopt.hp
    - hyperopt.tpe
    - hyperopt.pyll
    - hyperopt.pyll.stochastic

about:
  home: https://github.com/hyperopt/hyperopt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Distributed Asynchronous Hyper-parameter Optimization
  description: |
    Hyperopt is a Python library for serial and parallel optimization over awkward search spaces, 
    which may include real-valued, discrete, and conditional dimensions.
  doc_url: http://hyperopt.github.io/hyperopt/
  dev_url: https://github.com/hyperopt/hyperopt

extra:
  recipe-maintainers:
    - PhilipMay
