{% set name = "hyperopt" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hyperopt/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 91672206e7048c256ddff55a1ca4def95bb3d9199ead71605dba9a9c1ef29abf

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pymongo
    - six
    - networkx
    - future
    - tqdm
    - setuptools
    - cloudpickle    

test:
    imports:
        - hyperopt
        - hyperopt.fmin
        - hyperopt.hp
        - hyperopt.tpe
        - hyperopt.pyll
        - hyperopt.pyll.stochastic

about:
  home: https://github.com/hyperopt/hyperopt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Distributed Asynchronous Hyper-parameter Optimization'
  description: |
    Hyperopt is a Python library for serial and parallel optimization over awkward search spaces, 
    which may include real-valued, discrete, and conditional dimensions.
  doc_url: http://hyperopt.github.io/hyperopt/
  dev_url: https://github.com/hyperopt/hyperopt

extra:
  recipe-maintainers:
    - PhilipMay
