{% set name = "hyperopt" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hyperopt-{{ version }}.tar.gz
  sha256: 1bf89ae58050bbd32c7307199046117feee245c2fd9ab6255c7308522b7ca149

build:
  entry_points:
    - hyperopt-mongo-worker=hyperopt.mongoexp:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cloudpickle
    - future
    - networkx >=2.2
    - numpy >=1.17
    - py4j
    - python >={{ python_min }}
    - scipy
    - six
    - tqdm

test:
  imports:
    - hyperopt
  commands:
    - pip check
    - hyperopt-mongo-worker --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyperopt/hyperopt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Distributed Asynchronous Hyper-parameter Optimization
  description: |
    Hyperopt is a Python library for serial and parallel optimization over awkward search spaces,
    which may include real-valued, discrete, and conditional dimensions.
  doc_url: http://hyperopt.github.io/hyperopt/
  dev_url: https://github.com/hyperopt/hyperopt

extra:
  recipe-maintainers:
    - PhilipMay
    - BastianZim
